version: "3.8"

services:
  app:
    container_name: finance_tracker_app
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      DB_HOST: postgres
    depends_on:
      postgres:
        condition: service_healthy
    stdin_open: true
    tty: true
    networks:
      - finance_network
    command: >
      bash -c "
      until pg_isready -h ${DB_HOST} -p ${DB_PORT} -U ${DB_USER}; do
        echo 'Postgres is unavailable - sleeping';
        sleep 2;
      done;
      echo 'Postgres is up! Starting app';
      exec dotnet FinanceTrackerApp.dll
      "

  postgres:
    image: postgres:latest
    container_name: finance_tracker_postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - finance_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 2s
      timeout: 2s
      retries: 10

volumes:
  db_data:

networks:
  finance_network:
